- name: Deploy secrets
  hosts: all
  gather_facts: no

  tasks:

  - name: Get the secrets!
    include_vars: "{{secret_vault_location}}"

  - name: Test the templates are valid
    block:
      - name: test templating secrets file
        local_action: template src="{{secret_template_location}}" dest="secrettemp.php"
        check_mode: no
        diff: no
      - name: lint php files
        local_action: command php -l secrettemp.php | grep "No Syntax"
        check_mode: no
        diff: no
    always:
      - name: remove temp php files
        local_action: file state=absent path=secrettemp.php
        check_mode: no
        no_log: True

  - name: Template the secrets file
    template:
      src: "{{secret_template_location}}"
      dest: "{{secret_location}}"

  - name: Include secrets on local
    blockinfile:
      path: "{{localsettings_location}}"
      marker: "// {mark} added by ansible (secrets config)"
      mode: 0644
      block: |
        if (file_exists($dir . '/docroot/sites/default/settings/secrets.settings.local')) {
          require $dir . '/docroot/sites/default/settings/secrets.settings.local';
        }
    when:
      - localsettings_location is defined
      - not ansible_check_mode
